name = "farcastle-frames"
main = "src/index.tsx"
compatibility_date = "2024-09-23"
compatibility_flags = [ "nodejs_compat" ]

[site]
bucket = "./public"

[observability]
enabled = true

[vars]
ORIGIN = "https://frames.farcastle.net"

[env.staging]
name = "farcastle-frames-staging"

[env.staging.vars]
ORIGIN = "https://farcastle-frames-staging.earth2travis.workers.dev"



